# Generated by Django 4.2.20 on 2025-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imdb_url', models.URLField()),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('poster_url', models.URLField(blank=True)),
            ],
        ),
    ]
