# Generated by Django 4.2.20 on 2025-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('poster_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
