# Generated by Django 4.2.20 on 2025-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_favoritemovie_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=50, unique=True)),
                ('imdb_url', models.URLField()),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('plot', models.TextField()),
                ('poster', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
