# Generated by Django 4.2.20 on 2025-04-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_delete_favoritemovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
